development:
  adapter: mysql
  database: depot_development
  host: localhost
  username: 
  password: 

test:
  adapter: mysql
  database: depot_test
  host: localhost
  username: 
  password:

production:
  adapter: mysql
  database: depot_production
  host: localhost
  username: prod
  password: wibble
